embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  main:
    - public/stylesheets/grid.css
    - public/stylesheets/application.css
