embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery.tagbox.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/grid.css
    - public/stylesheets/tags.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/application.css
